# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coins_daily',
            field=models.FloatField(),
        ),
    ]
